license_id: "cc-by-igo"
notes: "Situation reports are the main reporting tool to monitor UNICEF’s humanitarian response. They provide an update on the situation and needs of children in a country or region, as well as information on UNICEF’s response and funding requirements."
caveats:
methodology: "Registry"
dataset_source: "UNICEF"
private: False
