# This workflow will install Python dependencies and run the script

name: Python package

on:
#  workflow_dispatch: # add run button in GitHub UI
#  schedule: #  Run script according to a cron schedule
#    - cron: "30 14 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      env: #  Environment variables mapped from GitHub repository's secrets to be used by script
        HDX_KEY: ${{ secrets.HDX_KEY }}
      run: |
        python run.py
#    Script output can be committed to the GitHub repository. The below would commit all
#    out*.json files to the repository.
#    - uses: stefanzweifel/git-auto-commit-action@v4
#      name: Commit updated data bundle
#      with:
#        file_pattern: out*.json
#        commit_message: automatic - Data bundle updated
#        push_options: '--force'